import styles from './EntryHeader.module.css';


const categories = ['INTERIOR', 'TRAVEL', 'STYLE', 'LIFESTYLE'];
const names = [
    "Avery Johnson",
    "Kai Thompson",
    "Harper Nguyen",
    "Luca Ramirez",
    "Riley Patel",
    "Emerson Brooks",
    "Rowan Wilson",
    "Jordan Kim",
    "Sage Hernandez",
    "Quinn Carter",
    "Parker Lee",
    "Skylar Murphy",
    "Taylor Bennett",
    "Finley Davis",
    "Morgan Foster",
    "Reese Sullivan",
    "Alexis Martin",
    "Dakota Reynolds",
    "Casey Parker",
    "Charlie Adams"
  ];

  const titles = [
    "17 Lessons I Learned From quitting my job",
    "The Harsh Truth About hustle culture",
    "How to Finally love your home Without changing everything",
    "24 Unexpected Ways to Upgrade Your Workspace",
    "10 Lessons I Learned From quitting my job",
    "The Harsh Truth About minimalism",
    "9 Things I Wish I Knew Before starting a blog",
    "Why You Should Stop procrastinating and Start doing",
    "18 Secrets to Becoming a organized minimalist",
    "6 Unexpected Ways to Change Your Home",
    "Who\u2019s Really Stopping You From quitting the 9-to-5?",
    "28 Secrets to Becoming a happier person",
    "17 Practical Ways to Organize Your Career",
    "How to Finally love your home Without changing everything",
    "6 Secrets to Becoming a happier person",
    "Why You Should Stop spending and Start appreciating",
    "10 Things I Wish I Knew Before starting a blog",
    "32 Things I Wish I Knew Before changing careers",
    "What It Feels Like to not worry about money",
    "Who\u2019s Really Stopping You From quitting the 9-to-5?",
    "What It Feels Like to stop comparing",
    "How to Finally reduce stress Without burning out",
    "What It Feels Like to love your space",
    "Why You Should Stop complaining and Start planning",
    "How to Finally travel more Without changing everything",
    "The Harsh Truth About hustle culture",
    "You Don\u2019t Need Permission to Start Over",
    "7 Lessons I Learned From decluttering my house",
    "You're Allowed to Want More Than 'Fine'",
    "Why You Should Stop worrying and Start living",
    "Why You Should Stop spending and Start living",
    "13 Lessons I Learned From traveling solo",
    "Who\u2019s Really Stopping You From quitting the 9-to-5?",
    "How to Finally dress confidently Without changing everything",
    "The Harsh Truth About work-life balance",
    "What It Feels Like to feel in control",
    "Who\u2019s Really Stopping You From being truly happy?",
    "The Harsh Truth About saving money",
    "Why You Should Stop spending and Start creating",
    "38 Simple Ways to Simplify Your Style",
    "3 Things I Wish I Knew Before changing careers",
    "The Harsh Truth About being productive",
    "How to Finally reduce stress Without burning out",
    "How to Finally love your home Without changing everything",
    "9 Practical Ways to Redesign Your Budget",
    "Why You Should Stop complaining and Start living",
    "What It Feels Like to not worry about money",
    "The Harsh Truth About hustle culture",
    "What It Feels Like to feel in control",
    "38 Lessons I Learned From decluttering my house",
    "How to Finally love your home Without changing everything",
    "28 Lessons I Learned From moving abroad",
    "The Harsh Truth About hustle culture",
    "6 Lessons I Learned From moving abroad",
    "13 Lessons I Learned From traveling solo",
    "20 Things I Wish I Knew Before buying a house",
    "You're Allowed to Want More Than 'Fine'",
    "The Harsh Truth About minimalism",
    "37 Things I Wish I Knew Before turning 30",
    "Who\u2019s Really Stopping You From quitting the 9-to-5?",
    "The Harsh Truth About being productive",
    "12 Things I Wish I Knew Before becoming a parent",
    "Your Own Advice Is the Hardest Pill to Swallow",
    "You Don\u2019t Need Permission to Start Over",
    "Why You Should Stop procrastinating and Start creating",
    "The Harsh Truth About being productive",
    "5 Proven Ways to Boost Your Style",
    "The Harsh Truth About work-life balance",
    "You're Allowed to Want More Than 'Fine'",
    "The Harsh Truth About minimalism",
    "36 Practical Ways to Upgrade Your Career",
    "4 Powerful Ways to Redesign Your Style",
    "The Harsh Truth About work-life balance",
    "36 Secrets to Becoming a organized minimalist",
    "Your Own Advice Is the Hardest Pill to Swallow",
    "32 Things I Wish I Knew Before starting a blog",
    "Who\u2019s Really Stopping You From moving where you want?",
    "The Harsh Truth About work-life balance",
    "Why You Should Stop overthinking and Start creating",
    "How to Finally travel more Without going broke",
    "Who\u2019s Really Stopping You From creating a life you love?",
    "37 Secrets to Becoming a organized minimalist",
    "29 Practical Ways to Boost Your Routine",
    "The Harsh Truth About minimalism",
    "How to Finally travel more Without burning out",
    "37 Secrets to Becoming a organized minimalist",
    "12 Secrets to Becoming a better planner",
    "24 Secrets to Becoming a better planner",
    "No One Tells You This About Success",
    "How to Finally dress confidently Without changing everything",
    "28 Secrets to Becoming a better planner",
    "5 Things I Wish I Knew Before becoming a parent",
    "The Harsh Truth About work-life balance",
    "How to Finally dress confidently Without burning out",
    "The Harsh Truth About minimalism",
    "34 Efficient Ways to Organize Your Workspace",
    "17 Secrets to Becoming a style icon",
    "Your Own Advice Is the Hardest Pill to Swallow",
    "You Don\u2019t Need Permission to Start Over",
    "What It Feels Like to not worry about money",
    "30 Powerful Ways to Simplify Your Life",
    "Who\u2019s Really Stopping You From living on your terms?",
    "13 Efficient Ways to Boost Your Style",
    "Who\u2019s Really Stopping You From moving where you want?",
    "32 Things I Wish I Knew Before starting a blog",
    "34 Lessons I Learned From decluttering my house",
    "Who\u2019s Really Stopping You From living on your terms?",
    "Who\u2019s Really Stopping You From being truly happy?",
    "How to Finally be financially free Without going broke",
    "13 Things I Wish I Knew Before starting a blog",
    "Why You Should Stop rushing and Start living",
    "15 Powerful Ways to Redesign Your Style",
    "How to Finally travel more Without going broke",
    "23 Lessons I Learned From quitting my job",
    "37 Lessons I Learned From moving abroad",
    "16 Things I Wish I Knew Before becoming a parent",
    "Why You Should Stop spending and Start appreciating",
    "Why You Should Stop procrastinating and Start planning",
    "The Harsh Truth About being productive",
    "No One Tells You This About Success",
    "17 Lessons I Learned From living with less",
    "No One Tells You This About Success",
    "Why You Should Stop procrastinating and Start planning",
    "This One Habit Changed Everything",
    "The Harsh Truth About being productive",
    "13 Lessons I Learned From moving abroad",
    "How to Finally be financially free Without selling your soul",
    "17 Simple Ways to Simplify Your Budget",
    "40 Secrets to Becoming a savvier traveler",
    "How to Finally dress confidently Without selling your soul",
    "Who\u2019s Really Stopping You From creating a life you love?",
    "What It Feels Like to love your space",
    "Who\u2019s Really Stopping You From moving where you want?",
    "This One Habit Changed Everything",
    "23 Proven Ways to Simplify Your Career",
    "You Don\u2019t Need Permission to Start Over",
    "What It Feels Like to wake up excited",
    "26 Things I Wish I Knew Before turning 30",
    "39 Things I Wish I Knew Before starting a blog",
    "7 Secrets to Becoming a organized minimalist",
    "The Harsh Truth About minimalism",
    "6 Lessons I Learned From moving abroad",
    "This One Habit Changed Everything",
    "Your Own Advice Is the Hardest Pill to Swallow",
    "The Harsh Truth About hustle culture",
    "Who\u2019s Really Stopping You From being truly happy?",
    "4 Things I Wish I Knew Before changing careers",
    "32 Easy Ways to Change Your Style",
    "40 Powerful Ways to Change Your Style",
    "The Harsh Truth About work-life balance",
    "26 Lessons I Learned From living with less",
    "23 Secrets to Becoming a happier person",
    "Who\u2019s Really Stopping You From being truly happy?",
    "What It Feels Like to love your space",
    "Why You Should Stop procrastinating and Start doing",
    "The Harsh Truth About hustle culture",
    "31 Unexpected Ways to Organize Your Routine",
    "The Harsh Truth About hustle culture",
    "14 Unexpected Ways to Boost Your Home",
    "33 Unexpected Ways to Simplify Your Style",
    "Who\u2019s Really Stopping You From creating a life you love?",
    "30 Secrets to Becoming a happier person",
    "Who\u2019s Really Stopping You From being truly happy?",
    "5 Things I Wish I Knew Before becoming a parent",
    "32 Efficient Ways to Change Your Workspace",
    "Who\u2019s Really Stopping You From creating a life you love?",
    "Why You Should Stop worrying and Start doing",
    "Why You Should Stop complaining and Start living",
    "9 Lessons I Learned From moving abroad",
    "The Harsh Truth About being productive",
    "What It Feels Like to stop comparing",
    "The Harsh Truth About hustle culture",
    "16 Secrets to Becoming a style icon",
    "37 Lessons I Learned From living with less",
    "31 Secrets to Becoming a savvier traveler",
    "21 Secrets to Becoming a style icon",
    "Who\u2019s Really Stopping You From being truly happy?",
    "You Don\u2019t Need Permission to Start Over",
    "14 Secrets to Becoming a organized minimalist",
    "The Harsh Truth About work-life balance",
    "How to Finally be financially free Without quitting your job",
    "31 Unexpected Ways to Redesign Your Life",
    "The Harsh Truth About work-life balance",
    "33 Lessons I Learned From decluttering my house",
    "Who\u2019s Really Stopping You From being truly happy?",
    "25 Secrets to Becoming a style icon",
    "How to Finally reduce stress Without changing everything",
    "14 Things I Wish I Knew Before becoming a parent",
    "9 Lessons I Learned From living with less",
    "27 Things I Wish I Knew Before buying a house",
    "30 Practical Ways to Redesign Your Life",
    "38 Things I Wish I Knew Before turning 30",
    "Why You Should Stop complaining and Start doing",
    "18 Secrets to Becoming a better planner",
    "28 Practical Ways to Boost Your Home",
    "What It Feels Like to not worry about money",
    "Why You Should Stop spending and Start doing",
    "How to Finally dress confidently Without changing everything",
    "Why You Should Stop complaining and Start living",
    "What It Feels Like to wake up excited",
    "22 Lessons I Learned From living with less",
    "The Harsh Truth About saving money",
    "How to Finally love your home Without burning out",
    "Who\u2019s Really Stopping You From quitting the 9-to-5?",
    "Who\u2019s Really Stopping You From living on your terms?",
    "13 Things I Wish I Knew Before becoming a parent",
    "20 Lessons I Learned From moving abroad",
    "How to Finally be financially free Without selling your soul",
    "21 Efficient Ways to Transform Your Budget",
    "Who\u2019s Really Stopping You From quitting the 9-to-5?",
    "12 Lessons I Learned From living with less",
    "19 Secrets to Becoming a style icon",
    "33 Powerful Ways to Simplify Your Style",
    "Who\u2019s Really Stopping You From living on your terms?",
    "8 Lessons I Learned From decluttering my house",
    "9 Things I Wish I Knew Before becoming a parent",
    "Who\u2019s Really Stopping You From creating a life you love?",
    "30 Things I Wish I Knew Before buying a house",
    "6 Things I Wish I Knew Before starting a blog",
    "31 Things I Wish I Knew Before becoming a parent",
    "How to Finally dress confidently Without going broke",
    "20 Lessons I Learned From quitting my job",
    "Who\u2019s Really Stopping You From being truly happy?",
    "No One Tells You This About Success",
    "The Harsh Truth About saving money",
    "How to Finally travel more Without burning out",
    "16 Secrets to Becoming a happier person",
    "Who\u2019s Really Stopping You From moving where you want?",
    "20 Easy Ways to Redesign Your Home",
    "3 Secrets to Becoming a happier person",
    "Your Own Advice Is the Hardest Pill to Swallow",
    "How to Finally be financially free Without quitting your job",
    "This One Habit Changed Everything",
    "34 Easy Ways to Upgrade Your Style",
    "How to Finally reduce stress Without burning out",
    "The Harsh Truth About being productive",
    "The Harsh Truth About hustle culture",
    "Why You Should Stop rushing and Start saving",
    "28 Practical Ways to Organize Your Style",
    "How to Finally be financially free Without quitting your job",
    "19 Things I Wish I Knew Before becoming a parent",
    "What It Feels Like to not worry about money",
    "11 Unexpected Ways to Redesign Your Home",
    "The Harsh Truth About being productive",
    "What It Feels Like to wake up excited",
    "How to Finally love your home Without changing everything",
    "27 Unexpected Ways to Boost Your Home",
    "9 Things I Wish I Knew Before turning 30",
    "Who\u2019s Really Stopping You From living on your terms?",
    "26 Easy Ways to Upgrade Your Routine"
  ]
  
export function randomizer() {
    return {
        category: categories[Math.floor(Math.random() * 4)],
        title: titles[Math.floor(Math.random() * 250)],
        name: names[Math.floor(Math.random() * 20)].toUpperCase()
    }
}

export function EntryHeader({ entry }) {
    const categoryLink = "/category/" + entry.category;
    const blogLink = "/blog/" + entry.title;
    const userLink = "/user/" + entry.name;
    const commentLink = userLink + "/comments/";

    return(
        <div className={styles["entry-preview-col"]}>
            <a href={categoryLink} className={styles["meta-category"]}>{entry.category}</a>
            <a href={blogLink} className={styles["entry-title"]}><h2 className={styles["entry-title"]}>{entry.title}</h2></a>
            <span className={styles["meta-post"]}><a href={userLink}>{entry.name}</a> • <a href="#">MAY 2024</a> • <a href={commentLink}>NO COMMENTS</a></span>
        </div>
    );
}

export default EntryHeader